--- #YAML:1.0
name:                HTTP-Cookies-iCab
version:             1.120
abstract:            Cookie storage and management for iCab 3
license:             perl
author:              
    - brian d foy <bdfoy@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    HTTP::Cookies:                 1.25
    Text::Diff:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
